[project]
name = "DiscordBot"
version = "0.1.0"
description = "DiscordBot"
readme = "README.md"
requires-python = ">=3.8, <4.0"

[tool.nonebot]
adapters = [
    { name = "Discord", module_name = "nonebot.adapters.discord" },
    {name = "QQ", module_name = "nonebot.adapters.qq"}
]
plugins = []
plugin_dirs = ["src/plugins"]
builtin_plugins = []
