name: Ruff Lint

on:
  push:
    branches:
      - main
    paths:
      - 'src/**'
  pull_request:

jobs:
  ruff:
    name: Ruff Lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Ruff Lint
        uses: chartboost/ruff-action@v1
        with:
          src: "./src"
